apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: crw-test-build
      labels:
        app.kubernetes.io/component: crw-test-build-pod
        app.kubernetes.io/instance: crw-test-build-1
        app.kubernetes.io/name: crw-test-build
        app.kubernetes.io/part-of: crw-test
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - name: build
          image: maven
          command: sleep
          args:
            - infinity
