apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: crw-test-dbms-config
      labels:
        app: crw-test
    immutable: true
    stringData:
      POSTGRES_DB: crw
      POSTGRES_PASSWORD: CRW123!
      POSTGRES_USER: crw
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: crw-test-dbms-data
      labels:
        app: crw-test
    data:
      setup.sql: |
        CREATE TABLE USERS (ID INTEGER PRIMARY KEY, FIRST_NAME VARCHAR(64), LAST_NAME VARCHAR(64), VERSION INTEGER DEFAULT 0);
        CREATE TABLE ACCOUNTS (USERNAME VARCHAR(32) PRIMARY KEY, PASSWORD VARCHAR(16), USER INTEGER REFERENCES USERS(ID), VERSION INTEGER DEFAULT 0);
        INSERT INTO USERS VALUES (0, 'Alessio Giovanni', 'Baroni');
        INSERT INTO ACCOUNTS VALUES ('alessio', 'Alessio123!', 0);
  - apiVersion: v1
    kind: Deployment
    metadata:
      name: crw-test-dbms
      labels:
        app: crw-test
    spec:
      selector:
        matchLabels:
          crw-test-component: dbms
      template:
        metadata:
          name: crw-test-dbms
          labels:
            crw-test-component: dbms
        spec:
          containers:
            - name: dbms
              image: postgres
              ports:
                - containerPort: 5432
              envFrom:
                - secretRef: dbms-config
              volumeMounts:
                - name: setup-data
                  mountPath: /docker-entrypoint-initdb.d
          volumes:
            - name: setup-data
              configMap:
                name: dbms-data
  - apiVersion: v1
    kind: Service
    metadata:
      name: crw-test-dbms
      labels:
        app: crw-test
    spec:
      selector:
        crw-test-component: dbms
      ports:
        - port: 5432
          targetPort: 5432
