apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: crw-test-app
      labels:
        app: crw-test
        crw-test-component: app
    spec:
      containers:
        - name: run
          image: openjdk:17
          command: sleep
          args:
            - infinity
          ports:
            - containerPort: 8080
  - apiVersion: v1
    kind: Service
    metadata:
      name: crw-test-app
      labels:
        app: crw-test
    spec:
      selector:
        crw-test-component: app
      ports:
        - port: 8080
          targetPort: 8080
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: crw-test-app
      labels:
        app: crw-test
    spec:
      to:
        kind: Service
        name: crw-test-app
      port:
        targetPort: 8080
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
