apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: crw-test-app
      labels:
        app.kubernetes.io/component: crw-test-app-pod
        app.kubernetes.io/instance: crw-test-app-1
        app.kubernetes.io/name: crw-test-app
        app.kubernetes.io/part-of: crw-test
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - name: run
          image: ubi8/openjdk-17
          command:
            - sleep
          args:
            - infinity
          ports:
            - containerPort: 8080
  - apiVersion: v1
    kind: Service
    metadata:
      name: crw-test-app
      labels:
        app.kubernetes.io/component: crw-test-app-service
        app.kubernetes.io/instance: crw-test-app-1
        app.kubernetes.io/name: crw-test-app
        app.kubernetes.io/part-of: crw-test
        app.kubernetes.io/version: 1.0.0
    spec:
      selector:
        app.kubernetes.io/component: crw-test-app-pod
      ports:
        - port: 8080
          targetPort: 8080
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: crw-test-app
      labels:
        app.kubernetes.io/component: crw-test-app-route
        app.kubernetes.io/instance: crw-test-app-1
        app.kubernetes.io/name: crw-test-app
        app.kubernetes.io/part-of: crw-test
        app.kubernetes.io/version: 1.0.0
    spec:
      to:
        kind: Service
        name: crw-test-app
      port:
        targetPort: 8080
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
